### PR TITLE
Fix image-tools install.sh link

### PR DESCRIPTION
**Pull request by onli**
The alternative would be of course to just update the http://j.mp/image-tools link, if he is controlled by you.

### CODE REVIEW

**Comment by moul** [comment]
Sorry guy, I can't accept your PR, this repository was not ported as we did on the other ones, and the future link won't look at this one

If you want a good start point, please use https://github.com/scaleway/image-app-docker instead of https://github.com/online-labs/image-app-wordpress as example image

I will port the missing online-labs/image-app-* repositories to scaleway with proper patches this week :)

Thanks again and nice work for you serendipity image :p

**Comment by onli** [comment]
Bot a problem. You mean that you want to use http://j.mp/scw-builder like in https://github.com/scaleway/image-app-docker/blob/master/Makefile#L13, or are the suggested changes bigger?

**Comment by moul** [comment]
The changes are bigger, look at this diff: https://github.com/scaleway/image-app-docker/compare/20da0263713de1bc6b0d085cf923035bc058191e...master

(it contains some non-related commits, but you see there are more changes :p)

I will port everything this week :)

**Comment by moul** [comment]
Fixed with this commit: https://github.com/scaleway/image-app-wordpress/commit/344e3e39dd301da323d832d73a60be8076958924

Now you can create PR without problem, thank you for your patience :)

**Comment by onli** [comment]
Yes, seems to be fixed. This is done :)

**Pull request closed without merging**
